# Site Information
title: "LLmachine"
email: "kent.sew@gmail.com"
description: >-
  Welcome to the LLmachine website. This platform shares insights and 
  advancements in data science, machine learning, data analysis, and 
  visualization. It provides valuable resources, showcases projects, and 
  engages with the data science community. Stay tuned for in-depth articles, 
  tutorials, and discussions.

baseurl: "" # Leave empty if hosting at the root (GitHub Pages)
url: "https://dataforsolution.github.io" # Ensure correct GitHub Pages URL

# Social Media Links
twitter_username: "SewLiben"
github_username: "Lissan"

# Author Information
author:
  name: "Lissan Liben"

# Build Settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Pagination Settings
paginate: 5  # Number of posts per page
permalink: pretty  # Use clean URLs (without .html extensions)

# Markdown Processor
markdown: kramdown

# Exclude these files from Jekyll processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Future settings and plugins can be added here
