# Site Information
title: "LLmachine"
email: "kent.sew@gmail.com"
description: >-
  Welcome to LLmachine, your hub for AI, data science, and analytics.
  Explore projects, insights, and professional research.

baseurl: ""  
url: "https://dataforsolution.github.io"  

# Theme and Plugins
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-include-cache  # Enables includes caching for better performance
  - jekyll-sitemap         # Generates a sitemap for better SEO
  - jekyll-assets          # Manages assets like CSS, JS, and images

# Pagination Settings
paginate: 5  
paginate_path: "/page:num/"  

# Markdown Processor
markdown: kramdown
kramdown:
  input: GFM # Enables GitHub-flavored markdown
  hard_wrap: false
  syntax_highlighter_opts:
    line_numbers: true

# Include and Exclude Paths
include:
  - _includes
  - _layouts
  - assets
  - .nojekyll
  - favicon.ico

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README.md

# Collections
collections:
  services:
    output: true
    permalink: /services/:path/
  projects:
    output: true
    permalink: /projects/:path/
  blog:
    output: true
    permalink: /blog/
  faq:
    output: true
    permalink: /faq/:path/
  contact:
    output: true
    permalink: /contact/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "LLmachine"
  - scope:
      path: "about"
    values:
      layout: "default"
      title: "About LLmachine"
  - scope:
      path: "services"
    values:
      layout: "default"
      title: "Our Services"

# Permalinks
permalink: pretty

# Sitemap Configuration
sitemap:
  exclude:
    - /404.html
  include:
    - /services/
    - /projects/
    - /blog/
    - /faq/
    - /contact/

# SEO Defaults
jekyll_seo_tag:
  social:
    twitter:
      username: "SewLiben"
    github:
      username: "DataForSolution"

# Performance Optimization
cache: true
